spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jeecg-boot?useSSL=false
    username: root
    password: zm123456


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
